quarkus:
  banner:
    enabled: false
  flyway:
    migrate-at-start: true
    locations: db/migration
  quinoa:
    enable-spa-routing: true


"%dev":
  quarkus:
    hibernate-orm:
      log:
        sql: true
    flyway:
      locations: db/migration,db/testdata
    keycloak:
      devservices:
        realm-path: test-realm.json
        port: 8081
    oidc:
      client-id: apicurio-svm-api
      credentials:
        secret: api-secret

"%test":
  quarkus:
    hibernate-orm:
      log:
        sql: true
    flyway:
      locations: db/migration,db/testdata
    keycloak:
      devservices:
        realm-path: test-realm.json
    oidc:
      client-id: apicurio-svm-api
      credentials:
        secret: api-secret
