quarkus:
  banner:
    enabled: false
  flyway:
    migrate-at-start: true


"%dev":
  quarkus:
    hibernate-orm:
      log:
        sql: true
    flyway:
      locations: db/migration,db/testdata

"%test":
  quarkus:
    hibernate-orm:
      log:
        sql: true
    flyway:
      locations: db/migration,db/testdata
